import Foundation

/// Manual device test checklist — run on a real phone after each release candidate.
enum DeviceTestChecklist {
    static let items = [
        "30+ min real drive: distance and duration advance",
        "Background the app, wait 5 min: recording continues",
        "Shortcuts: recording starts when connecting to the car",
        "Shortcuts: Start trip Vehicle param — CarPlay vs Bluetooth automations assign different vehicles",
        "Shortcuts: recording stops when leaving the car",
        "Force-quit → reopen → orphan banner / recovery",
        "Detail map route looks realistic (does not cross water)",
        "Pairing: typing a vehicle name keeps the keyboard smooth",
        "While recording, switching away from Trips reduces jank",
        "Long trip detail opens without freezing",
        "Trip detail edit fields: place/address/fuel/note stay above keyboard accessory; title chip hugs text (not full-bleed); Tamam glass chip; map does not jump; scroll dismisses keyboard; Reduce Motion settles instantly",
        "Form sheets (expense/schedule/settings/place/pairing): title chip + glass Tamam on first focus; tap/scroll dismiss; Trip Detail still grows panel without map jump",
        "Trip list search: keyboard shows hug-content title chip + glass Tamam; tap/scroll also dismisses",
        "50 km trip detail: DevLog points/displayPts/colorSegs; colorSegs ≤ 60",
        "500 km trip detail (if available): opens smoothly, curves not oversimplified",
        "Second open of the same long trip is instant (memory cache)",
        "App kill → reopen → long trip detail still fast (disk cache)",
        "After GPS trim, map updates (cache invalidation)",
        "After merge, combined route draws correctly",
        "Trip with tunnel/signal loss keeps a broken route (no bird-flight fill)",
        "Start-side Select: photo/icon + chevron only; no name text overflow",
        "Recording card: large vehicle photo; Stop uses stop.fill",
        "Recording card: trip start — live-map chip pops into a localized “Switch to map mode” / “Harita moduna geçin” capsule, then collapses to a pulsing map chip; tap still opens live follow",
        "Live follow map: open — map already at follow pose (no world fly-in); map fade + vehicle→puck hero sync; compact HUD at bottom (Pause/Stop TR single-line; 2D/3D tappable)",
        "Live follow map: open at highway speed — curved vehicle→puck flight lands on the moving puck; blue path does not race ahead of a frozen camera",
        "Live follow map: X reverses (map fades out while nav puck flies back to list-card vehicle); Stop skips reverse and plays end credits",
        "Live follow map: Reduce Motion opens/closes instantly settled; blue path still visible on open",
        "Live follow map: open with existing breadcrumbs — blue path visible in the first frame (no blank hold-back window)",
        "Live follow map: pan/recenter → pause/stop; 3D/2D switch; overview/follow switch fits start+trail vs re-locks; single annotation puck stays visible after pan (no second pointer, never disappears)",
        "Live follow map: smooth camera on straight road and turns (continuous between GPS fixes, no 1 Hz hitch / no rewind)",
        "Live follow map: highway — camera, vehicle mark, and blue path glide together (no 1 Hz stall, no chunky trail at the puck)",
        "Live follow map: single draped blue path (chunked history + growing tail tip) grows with the puck; no duplicate / X crossover; real GPS gaps only",
        "Live follow map: stroke keeps the same thickness in 2D and 3D, and stays uniform end-to-end while panning a pitched camera",
        "Live follow map: pan while recording — trail stays; puck + tip keep advancing when moving; overview fits whole route; recenter re-locks camera; pause locks pan and 2D/3D tools",
        "Live follow map: Show entire route (north-up) — vehicle photo + chevron sharp tip still face travel; recenter returns screen-up follow",
        "Live follow map: highway speed — camera pulls back; blue path stays behind the puck (does not draw ahead); motion glides between 1 Hz GPS fixes with no chunky trail at the puck",
        "Live follow map: leave untouched 30–60s — screen stays awake; close map — auto-lock works again",
        "Live follow map: green start pin at first point; orange pause pin at each pause (stays after resume)",
        "Vespa / motorcycle / car markers face right on the road",
        "Dynamic Island + lock banner: vehicle photo or correct SF; facing right",
        "CarPlay Live Activity tile: after 1+ hour / long km, Duration Distance Speed stay the same size, centered in their columns, no overlap; car icon size unchanged",
        "Notifications: live recording card shows road + photo + controls",
        "Pause/resume: no road remount; Island photo stays",
        "Home-screen widget: Pause → Resume label flips; Resume → Pause returns",
        "Lock banner pause/resume: icon+color immediate; widget switches to Resume",
        "Recording with vehicle photo: Island shows photo; DevLog ‘photo attached (N B)’",
        "Light/white vehicle photo: if punch makes it vanish, original photo is shown",
        "Vehicle without photo: Island + notification card fall back to SF symbol",
        "Expanded Island: no top gap; bottom buttons not clipped (even at 1:00:10)",
        "Vehicle picker menu: no row icons; checkmark only on the selected vehicle",
        "Vehicle photo: Add → Library/Camera chooser; Library/Camera single sheet expand (~72%), no dismiss/reopen",
        "Vehicle photo: Capture Back → shrinks to chooser; Cancel on chooser dismisses sheet",
        "Vehicle photo: All Photos system picker; framing after pick",
        "Vehicle photo: camera shutter; green privacy dot clears when backgrounded",
        "Vehicle photo: limited library / deny photos / deny camera states",
        "Vehicle photo: Change + existing framing Apply/Save path still works",
        "Trip detail: Travel time (moving, excluding stops) sits beside Duration; ? explains the difference",
        "Trip detail: cards pack left-to-right with no empty mid-grid slots; Avg fuel calculate ? explains catalog cost; preview is Avg fuel calculation; Avg fuel and Est. fuel both show cost · volume; Est. ? opens full explanation",
        "Trip detail / Stats: Cruise + Common ? explain moving average vs pace band; Median + P90 when route loaded",
        "Stats summary: Total est. fuel and daily dual fuel chart readable (labels not overlapping)",
        "Cold open / onboarding: Trailhound logo 96 pt sharp; not blurry or pixelated",
        "Home screen icon matches previous look (corners, colors, halo)",
        "Recording start/stop sounds play; same tone as before, no cut-off"
    ]
}
