import Foundation

/// Manual device test checklist — run on a real phone after each release candidate.
enum DeviceTestChecklist {
    static let items = [
        "30+ min real drive: distance and duration advance",
        "Background the app, wait 5 min: recording continues",
        "Shortcuts: recording starts when connecting to the car",
        "Shortcuts: recording stops when leaving the car",
        "Force-quit → reopen → orphan banner / recovery",
        "Detail map route looks realistic (does not cross water)",
        "Pairing: typing a vehicle name keeps the keyboard smooth",
        "While recording, switching away from Trips reduces jank",
        "Long trip detail opens without freezing",
        "Trip detail edit fields: place/address/fuel/note stay above keyboard accessory; title chip hugs text (not full-bleed); Tamam glass chip; map does not jump; scroll dismisses keyboard; Reduce Motion settles instantly",
        "Form sheets (expense/schedule/settings/place/pairing): title chip + glass Tamam on first focus; tap/scroll dismiss; Trip Detail still grows panel without map jump",
        "Trip list search: keyboard shows hug-content title chip + glass Tamam; tap/scroll also dismisses",
        "50 km trip detail: DevLog points/displayPts/colorSegs; colorSegs ≤ 60",
        "500 km trip detail (if available): opens smoothly, curves not oversimplified",
        "Second open of the same long trip is instant (memory cache)",
        "App kill → reopen → long trip detail still fast (disk cache)",
        "After GPS trim, map updates (cache invalidation)",
        "After merge, combined route draws correctly",
        "Trip with tunnel/signal loss keeps a broken route (no bird-flight fill)",
        "Start-side Select: photo/icon + chevron only; no name text overflow",
        "Recording card: large vehicle photo; Stop uses stop.fill",
        "Live follow map: open — map already at follow pose (no world fly-in); map fade + vehicle→puck hero sync; HUD at bottom",
        "Live follow map: X reverses (map fades out while nav puck flies back to list-card vehicle); Stop skips reverse and plays end credits",
        "Live follow map: Reduce Motion opens/closes instantly settled",
        "Live follow map: pan/recenter → pause/stop; 3D/2D toggle; chevron + vehicle puck aims with heading",
        "Live follow map: smooth camera on straight road and turns (no steppy 4 Hz jumps)",
        "Live follow map: leave untouched 30–60s — screen stays awake; close map — auto-lock works again",
        "Live follow map: green start pin at first point; orange pause pin at each pause (stays after resume)",
        "Vespa / motorcycle / car markers face right on the road",
        "Dynamic Island + lock banner: vehicle photo or correct SF; facing right",
        "Notifications: live recording card shows road + photo + controls",
        "Pause/resume: no road remount; Island photo stays",
        "Home-screen widget: Pause → Resume label flips; Resume → Pause returns",
        "Lock banner pause/resume: icon+color immediate; widget switches to Resume",
        "Recording with vehicle photo: Island shows photo; DevLog ‘photo attached (N B)’",
        "Light/white vehicle photo: if punch makes it vanish, original photo is shown",
        "Vehicle without photo: Island + notification card fall back to SF symbol",
        "Expanded Island: no top gap; bottom buttons not clipped (even at 1:00:10)",
        "Vehicle picker menu: no row icons; checkmark only on the selected vehicle",
        "Vehicle photo: Add → Library/Camera chooser; Library/Camera single sheet expand (~72%), no dismiss/reopen",
        "Vehicle photo: Capture Back → shrinks to chooser; Cancel on chooser dismisses sheet",
        "Vehicle photo: All Photos system picker; framing after pick",
        "Vehicle photo: camera shutter; green privacy dot clears when backgrounded",
        "Vehicle photo: limited library / deny photos / deny camera states",
        "Vehicle photo: Change + existing framing Apply/Save path still works",
        "Trip detail: Avg fuel and Est. fuel both show; Est. ? opens full explanation",
        "Trip detail / Stats: Cruise + Common ? explain moving average vs pace band; Median + P90 when route loaded",
        "Stats summary: Total est. fuel and daily dual fuel chart readable (labels not overlapping)"
    ]
}
